name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses:  action-python/pyinstaller-py3.8@v1.0.0
    - name: Set up Python 3.x
      uses:  action-python/pyinstaller-py3.8@v1.0.0
      with:
        python-version: '3.8' # 选择你想要使用的 Python 版本
    - name: Run start.py
      run: |
        python start.py
